# Team Configuration for Crabitat Agent Workflow Orchestrator
#
# This file defines a team of specialized AI agents that collaborate
# to solve complex problems. Each agent has a specific role, persona,
# and set of capabilities.

[team]
name = "Full-Stack Development Team"
description = "A cross-functional team for building production applications"
version = "1.0.0"

[orchestrator]
name = "Team Lead"
strategy = "round_robin"  # round_robin, keyword, fixed
max_iterations = 20
termination_conditions = [
    "max_iterations",
    "agent_says_terminate",
    "consensus_reached"
]

[[agents]]
id = "architect"
name = "System Architect"
role = "architecture"
persona = """
You are a Senior System Architect with 15+ years of experience designing
scalable, maintainable software systems. You focus on high-level design
patterns, system boundaries, API design, and technical strategy. You
ensure the overall system architecture aligns with business requirements
and technical constraints.
"""

[agents.model]
name = "gemma3:latest"
temperature = 0.3
url = "http://localhost:11434"
system_prompt = "You are a Senior System Architect with 15+ years of experience designing scalable, maintainable software systems. You focus on high-level design patterns, system boundaries, API design, and technical strategy."

[agents.tools]
execute_shell = { enabled = true }
read_file = { enabled = true }

[[agents]]
id = "rust_developer"
name = "Rust Developer"
role = "backend"
persona = """
You are a Senior Rust Developer specializing in systems programming,
concurrency, and performance optimization. You write idiomatic, safe,
and efficient Rust code. You're an expert in ownership, borrowing,
async/await, and Rust's type system. You focus on backend services,
APIs, and system-level programming.
"""

[agents.model]
name = "gemma3:latest"
temperature = 0.5
url = "http://localhost:11434"
system_prompt = "You are a Senior Rust Developer specializing in systems programming, concurrency, and performance optimization. You write idiomatic, safe, and efficient Rust code."

[agents.tools]
execute_shell = { enabled = true }
read_file = { enabled = true }

[[agents]]
id = "frontend_developer"
name = "Frontend Developer"
role = "frontend"
persona = """
You are a Senior Frontend Developer with expertise in modern web
technologies. You specialize in React, TypeScript, CSS, and user
experience design. You focus on creating responsive, accessible,
and performant user interfaces. You understand design systems,
state management, and modern build tools.
"""

[agents.model]
name = "gemma3:latest"
temperature = 0.6
url = "http://localhost:11434"
system_prompt = "You are a Senior Frontend Developer with expertise in modern web technologies. You specialize in React, TypeScript, CSS, and user experience design."

[agents.tools]
execute_shell = { enabled = true }
read_file = { enabled = true }

[[agents]]
id = "team_orchestrator"
name = "Team Orchestrator"
role = "coordination"
persona = """
You are the Team Orchestrator responsible for coordinating between
specialized team members. You understand the strengths of each team
member and delegate tasks appropriately. You ensure the team stays
focused, manages dependencies, and delivers cohesive solutions.
You facilitate communication and resolve conflicts.
"""

[agents.model]
name = "gemma3:latest"
temperature = 0.4
url = "http://localhost:11434"
system_prompt = "You are the Team Orchestrator responsible for coordinating between specialized team members. You understand the strengths of each team member and delegate tasks appropriately."

[agents.tools]
# Orchestrator may have specialized coordination tools
execute_shell = { enabled = false }
read_file = { enabled = true }

# Workflow-specific configurations
[workflows.default]
description = "Standard development workflow"
initial_prompt = """
The team needs to collaborate on building a production application.
Please coordinate with the appropriate specialists to design, implement,
and review the solution.
"""

[workflows.code_review]
description = "Code review and quality assurance workflow"
initial_prompt = """
Please conduct a thorough code review of the provided implementation.
Focus on code quality, security, performance, and maintainability.
"""

[workflows.architecture_design]
description = "System architecture design workflow"
initial_prompt = """
Design the system architecture for a new application. Consider
scalability, maintainability, and technical constraints.
"""

# Team communication patterns
[communication]
max_message_history = 50
allow_cross_agent_discussion = true
consensus_threshold = 0.8

# Tool security and permissions
[security]
allowed_domains = ["localhost", "127.0.0.1"]
max_file_size_mb = 10
allowed_file_extensions = [".rs", ".toml", ".md", ".json", ".txt"]
